version: "3.9"

services:
  # blazor:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: blazor_app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - ASPNETCORE_URLS=http://+:8080
  #     - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BlazorDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
  #   depends_on:
  #     - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin12345#
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
